In [1]:
from futu import *

In [2]:
quote_ctx = OpenQuoteContext(host='127.0.0.1', port=11111)

2021-06-29 00:31:52,485 [open_context_base.py] _socket_reconnect_and_wait_ready:258: Start connecting: host=127.0.0.1; port=11111;
2021-06-29 00:31:52,512 [open_context_base.py] on_connected:349: Connected : conn_id=1;
2021-06-29 00:31:52,517 [open_context_base.py] _handle_init_connect:454: InitConnect ok: conn_id=1; info={'server_version': 504, 'login_user_id': 16588498, 'conn_id': 6815315813942644905, 'conn_key': 'CD79499AC8931CE0', 'conn_iv': '007BE36088FAF9DE', 'keep_alive_interval': 10, 'is_encrypt': False};

In [19]:
req = WarrantRequest()
req.sort_field = SortField.TURNOVER
req.type_list = WrtType.BULL

ret, ls = quote_ctx.get_warrant("HK.09988", req)
if ret == RET_OK:  # 先判断接口返回是否正常，再取数据
    warrant_data_list, last_page, all_count = ls
else:
    print('error: ', ls)

In [20]:
warrant_data_list.head()

,stock,name,stock_owner,type,issuer,maturity_time,list_time,last_trade_time,recovery_price,conversion_ratio,...,low_price,implied_volatility,delta,effective_leverage,list_timestamp,last_trade_timestamp,maturity_timestamp,upper_strike_price,lower_strike_price,inline_price_status
0,HK.62371,阿里摩通一八牛C.C,HK.09988,BULL,JP,2021-08-13,2020-12-30,2021-08-12,192.80,500.0,...,0.0,NaN,NaN,6.434,1.609258e+09,1.628698e+09,1.628784e+09,NaN,NaN,NaN
1,HK.62806,阿里汇丰一甲牛A.C,HK.09988,BULL,HS,2021-11-30,2020-12-31,2021-11-29,168.88,500.0,...,0.0,NaN,NaN,3.929,1.609344e+09,1.638115e+09,1.638202e+09,NaN,NaN,NaN
2,HK.63170,阿里中银一六牛I.C,HK.09988,BULL,BI,2021-06-30,2020-12-31,2021-06-29,188.88,100.0,...,0.0,NaN,NaN,6.253,1.609344e+09,1.624896e+09,1.624982e+09,NaN,NaN,NaN
3,HK.60703,阿里汇丰一乙牛C.C,HK.09988,BULL,HS,2021-12-30,2021-01-12,2021-12-29,158.88,500.0,...,0.0,NaN,NaN,3.338,1.610381e+09,1.640707e+09,1.640794e+09,NaN,NaN,NaN
4,HK.60958,阿里瑞信一十牛K.C,HK.09988,BULL,CS,2021-10-28,2021-05-14,2021-10-27,185.00,100.0,...,0.0,NaN,NaN,5.481,1.620922e+09,1.635264e+09,1.635350e+09,NaN,NaN,NaN

In [9]:
warrant_data_list.columns

Index(['stock', 'name', 'stock_owner', 'type', 'issuer', 'maturity_time',
       'list_time', 'last_trade_time', 'recovery_price', 'conversion_ratio',
       'lot_size', 'strike_price', 'last_close_price', 'cur_price',
       'price_change_val', 'change_rate', 'status', 'bid_price', 'ask_price',
       'bid_vol', 'ask_vol', 'volume', 'turnover', 'score', 'premium',
       'break_even_point', 'leverage', 'ipop', 'price_recovery_ratio',
       'conversion_price', 'street_rate', 'street_vol', 'amplitude',
       'issue_size', 'high_price', 'low_price', 'implied_volatility', 'delta',
       'effective_leverage', 'list_timestamp', 'last_trade_timestamp',
       'maturity_timestamp', 'upper_strike_price', 'lower_strike_price',
       'inline_price_status'],
      dtype='object')

In [23]:
warrant_data_list['recovery_price'].to_list()

[192.8,
 168.88,
 188.88,
 158.88,
 185.0,
 202.88,
 202.88,
 203.0,
 203.0,
 203.0,
 204.0,
 205.0,
 206.0,
 205.8,
 205.8,
 202.8,
 203.0,
 205.88,
 204.0,
 180.0,
 178.0,
 207.0,
 209.0,
 205.8,
 209.0,
 205.0,
 208.88,
 203.88,
 215.0,
 210.0,
 215.0,
 210.0,
 208.88,
 214.0,
 210.0,
 193.0,
 170.0,
 180.88,
 198.88,
 175.0,
 203.0,
 170.0,
 184.8,
 162.8,
 195.0,
 150.0,
 146.0,
 180.0,
 178.0,
 188.88,
 192.0,
 190.0,
 202.0,
 160.0,
 186.18,
 182.88,
 172.8,
 178.88,
 170.88,
 173.88,
 191.5,
 195.88,
 192.0,
 158.0,
 174.18,
 197.0,
 195.0,
 199.0,
 195.0,
 192.88,
 185.0,
 181.5,
 195.0,
 182.8,
 192.8,
 183.88,
 196.8,
 165.0,
 180.0,
 185.0,
 175.0,
 195.0,
 203.0,
 185.0,
 183.0,
 180.0,
 185.88,
 198.88,
 190.18,
 170.0,
 160.0,
 200.0,
 195.88,
 195.0,
 160.0,
 190.0,
 170.0,
 168.0,
 188.88,
 190.0,
 200.0,
 206.0,
 200.18,
 207.0,
 200.0,
 181.5,
 198.88,
 196.0,
 201.0,
 198.88,
 200.0,
 193.88,
 190.0,
 191.38,
 202.0,
 198.0,
 203.0,
 198.0,
 198.0,
 185.0,
 204.0,
 200.0]

In [21]:
warrant_data_list.to_excel('warrant_9988_bull.xlsx')

In [22]:
quote_ctx.close()  # 所有接口结尾加上这条 close，防止连接条数用尽

2021-06-29 01:00:24,319 [network_manager.py] work:366: Close: conn_id=1